USE [master]
GO

/****** Object:  Database [Athletics]    Script Date: 27/11/2022 20:46:27 ******/
CREATE DATABASE [Athletics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Athletics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Athletics.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Athletics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Athletics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Athletics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Athletics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Athletics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Athletics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Athletics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Athletics] SET ARITHABORT OFF 
GO

ALTER DATABASE [Athletics] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Athletics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Athletics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Athletics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Athletics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Athletics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Athletics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Athletics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Athletics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Athletics] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Athletics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Athletics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Athletics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Athletics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Athletics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Athletics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Athletics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Athletics] SET RECOVERY FULL 
GO

ALTER DATABASE [Athletics] SET  MULTI_USER 
GO

ALTER DATABASE [Athletics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Athletics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Athletics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Athletics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Athletics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Athletics] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Athletics] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Athletics] SET  READ_WRITE 
GO

